Add Make functionalities. - Add custom flag to control static/dynamic linking. - Add install target to perform compilation and copy to DESTDIR afterwards.

diff --git a/lab-02/app/Makefile b/lab-02/app/Makefile
--- a/lab-02/app/Makefile
+++ b/lab-02/app/Makefile
@@ -1,7 +1,16 @@
 CFLAGS := -Wall -I./inc
-LDFLAGS := -static -ltest -L./lib
+STATIC ?= 1
 
-app: src/app.o lib/libtest.a
+ifeq ($(STATIC), 1)
+    LDFLAGS := -static -L./lib -ltest
+    DEPS := src/app.o lib/libtest.a
+else
+    LDFLAGS := -L./lib -ltest -Wl,-rpath,./lib
+    DEPS := src/app.o lib/libtest.so
+endif
+
+
+app: $(DEPS)
 	$(CROSS_COMPILE)gcc src/app.o -o $@ $(LDFLAGS)
 
 src/app.o: src/app.c
@@ -10,9 +19,21 @@ src/app.o: src/app.c
 lib/libtest.a:
 	$(MAKE) -C lib libtest.a
 
+lib/libtest.so:
+	$(MAKE) -C lib libtest.so
+
 clean:
 	rm -f app src/*.o
 	$(MAKE) -C lib clean
 
-.PHONY: clean
+install: app
+	@if [ ! -d "$(DESTDIR)" ]; then \
+		echo "Error: Directory $(DESTDIR) not foudn!"; \
+		exit 1; \
+	fi
+	cp app $(DESTDIR)
+	sync
+	@echo "Executable copied successfully."
+
+.PHONY: clean install
 
